//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetCountriesService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="GetCountriesService.countrySoap")]
    public interface countrySoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCountryByCountryCode", ReplyAction="*")]
        System.Threading.Tasks.Task<GetCountriesService.GetCountryByCountryCodeResponse> GetCountryByCountryCodeAsync(GetCountriesService.GetCountryByCountryCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetISD", ReplyAction="*")]
        System.Threading.Tasks.Task<GetCountriesService.GetISDResponse> GetISDAsync(GetCountriesService.GetISDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<GetCountriesService.GetCountriesResponse> GetCountriesAsync(GetCountriesService.GetCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCurrencyCodeByCurrencyName", ReplyAction="*")]
        System.Threading.Tasks.Task<GetCountriesService.GetCurrencyCodeByCurrencyNameResponse> GetCurrencyCodeByCurrencyNameAsync(GetCountriesService.GetCurrencyCodeByCurrencyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetISOCountryCodeByCountyName", ReplyAction="*")]
        System.Threading.Tasks.Task<GetCountriesService.GetISOCountryCodeByCountyNameResponse> GetISOCountryCodeByCountyNameAsync(GetCountriesService.GetISOCountryCodeByCountyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCurrencyCode", ReplyAction="*")]
        System.Threading.Tasks.Task<GetCountriesService.GetCurrencyCodeResponse> GetCurrencyCodeAsync(GetCountriesService.GetCurrencyCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCountryByCurrencyCode", ReplyAction="*")]
        System.Threading.Tasks.Task<GetCountriesService.GetCountryByCurrencyCodeResponse> GetCountryByCurrencyCodeAsync(GetCountriesService.GetCountryByCurrencyCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCurrencies", ReplyAction="*")]
        System.Threading.Tasks.Task<GetCountriesService.GetCurrenciesResponse> GetCurrenciesAsync(GetCountriesService.GetCurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCurrencyByCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<GetCountriesService.GetCurrencyByCountryResponse> GetCurrencyByCountryAsync(GetCountriesService.GetCurrencyByCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetGMTbyCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<GetCountriesService.GetGMTbyCountryResponse> GetGMTbyCountryAsync(GetCountriesService.GetGMTbyCountryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCountryCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCountryCode", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCountryByCountryCodeRequestBody Body;
        
        public GetCountryByCountryCodeRequest()
        {
        }
        
        public GetCountryByCountryCodeRequest(GetCountriesService.GetCountryByCountryCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetCountryByCountryCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CountryCode;
        
        public GetCountryByCountryCodeRequestBody()
        {
        }
        
        public GetCountryByCountryCodeRequestBody(string CountryCode)
        {
            this.CountryCode = CountryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCountryCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCountryCodeResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCountryByCountryCodeResponseBody Body;
        
        public GetCountryByCountryCodeResponse()
        {
        }
        
        public GetCountryByCountryCodeResponse(GetCountriesService.GetCountryByCountryCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetCountryByCountryCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCountryByCountryCodeResult;
        
        public GetCountryByCountryCodeResponseBody()
        {
        }
        
        public GetCountryByCountryCodeResponseBody(string GetCountryByCountryCodeResult)
        {
            this.GetCountryByCountryCodeResult = GetCountryByCountryCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetISDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetISD", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetISDRequestBody Body;
        
        public GetISDRequest()
        {
        }
        
        public GetISDRequest(GetCountriesService.GetISDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetISDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CountryName;
        
        public GetISDRequestBody()
        {
        }
        
        public GetISDRequestBody(string CountryName)
        {
            this.CountryName = CountryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetISDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetISDResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetISDResponseBody Body;
        
        public GetISDResponse()
        {
        }
        
        public GetISDResponse(GetCountriesService.GetISDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetISDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetISDResult;
        
        public GetISDResponseBody()
        {
        }
        
        public GetISDResponseBody(string GetISDResult)
        {
            this.GetISDResult = GetISDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountries", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCountriesRequestBody Body;
        
        public GetCountriesRequest()
        {
        }
        
        public GetCountriesRequest(GetCountriesService.GetCountriesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCountriesRequestBody
    {
        
        public GetCountriesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCountriesResponseBody Body;
        
        public GetCountriesResponse()
        {
        }
        
        public GetCountriesResponse(GetCountriesService.GetCountriesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetCountriesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCountriesResult;
        
        public GetCountriesResponseBody()
        {
        }
        
        public GetCountriesResponseBody(string GetCountriesResult)
        {
            this.GetCountriesResult = GetCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyCodeByCurrencyNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyCodeByCurrencyName", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCurrencyCodeByCurrencyNameRequestBody Body;
        
        public GetCurrencyCodeByCurrencyNameRequest()
        {
        }
        
        public GetCurrencyCodeByCurrencyNameRequest(GetCountriesService.GetCurrencyCodeByCurrencyNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetCurrencyCodeByCurrencyNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CurrencyName;
        
        public GetCurrencyCodeByCurrencyNameRequestBody()
        {
        }
        
        public GetCurrencyCodeByCurrencyNameRequestBody(string CurrencyName)
        {
            this.CurrencyName = CurrencyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyCodeByCurrencyNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyCodeByCurrencyNameResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCurrencyCodeByCurrencyNameResponseBody Body;
        
        public GetCurrencyCodeByCurrencyNameResponse()
        {
        }
        
        public GetCurrencyCodeByCurrencyNameResponse(GetCountriesService.GetCurrencyCodeByCurrencyNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetCurrencyCodeByCurrencyNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrencyCodeByCurrencyNameResult;
        
        public GetCurrencyCodeByCurrencyNameResponseBody()
        {
        }
        
        public GetCurrencyCodeByCurrencyNameResponseBody(string GetCurrencyCodeByCurrencyNameResult)
        {
            this.GetCurrencyCodeByCurrencyNameResult = GetCurrencyCodeByCurrencyNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetISOCountryCodeByCountyNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetISOCountryCodeByCountyName", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetISOCountryCodeByCountyNameRequestBody Body;
        
        public GetISOCountryCodeByCountyNameRequest()
        {
        }
        
        public GetISOCountryCodeByCountyNameRequest(GetCountriesService.GetISOCountryCodeByCountyNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetISOCountryCodeByCountyNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CountryName;
        
        public GetISOCountryCodeByCountyNameRequestBody()
        {
        }
        
        public GetISOCountryCodeByCountyNameRequestBody(string CountryName)
        {
            this.CountryName = CountryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetISOCountryCodeByCountyNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetISOCountryCodeByCountyNameResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetISOCountryCodeByCountyNameResponseBody Body;
        
        public GetISOCountryCodeByCountyNameResponse()
        {
        }
        
        public GetISOCountryCodeByCountyNameResponse(GetCountriesService.GetISOCountryCodeByCountyNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetISOCountryCodeByCountyNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetISOCountryCodeByCountyNameResult;
        
        public GetISOCountryCodeByCountyNameResponseBody()
        {
        }
        
        public GetISOCountryCodeByCountyNameResponseBody(string GetISOCountryCodeByCountyNameResult)
        {
            this.GetISOCountryCodeByCountyNameResult = GetISOCountryCodeByCountyNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyCode", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCurrencyCodeRequestBody Body;
        
        public GetCurrencyCodeRequest()
        {
        }
        
        public GetCurrencyCodeRequest(GetCountriesService.GetCurrencyCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCurrencyCodeRequestBody
    {
        
        public GetCurrencyCodeRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyCodeResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCurrencyCodeResponseBody Body;
        
        public GetCurrencyCodeResponse()
        {
        }
        
        public GetCurrencyCodeResponse(GetCountriesService.GetCurrencyCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetCurrencyCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrencyCodeResult;
        
        public GetCurrencyCodeResponseBody()
        {
        }
        
        public GetCurrencyCodeResponseBody(string GetCurrencyCodeResult)
        {
            this.GetCurrencyCodeResult = GetCurrencyCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCurrencyCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCurrencyCode", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCountryByCurrencyCodeRequestBody Body;
        
        public GetCountryByCurrencyCodeRequest()
        {
        }
        
        public GetCountryByCurrencyCodeRequest(GetCountriesService.GetCountryByCurrencyCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetCountryByCurrencyCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CurrencyCode;
        
        public GetCountryByCurrencyCodeRequestBody()
        {
        }
        
        public GetCountryByCurrencyCodeRequestBody(string CurrencyCode)
        {
            this.CurrencyCode = CurrencyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCurrencyCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCurrencyCodeResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCountryByCurrencyCodeResponseBody Body;
        
        public GetCountryByCurrencyCodeResponse()
        {
        }
        
        public GetCountryByCurrencyCodeResponse(GetCountriesService.GetCountryByCurrencyCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetCountryByCurrencyCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCountryByCurrencyCodeResult;
        
        public GetCountryByCurrencyCodeResponseBody()
        {
        }
        
        public GetCountryByCurrencyCodeResponseBody(string GetCountryByCurrencyCodeResult)
        {
            this.GetCountryByCurrencyCodeResult = GetCountryByCurrencyCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencies", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCurrenciesRequestBody Body;
        
        public GetCurrenciesRequest()
        {
        }
        
        public GetCurrenciesRequest(GetCountriesService.GetCurrenciesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCurrenciesRequestBody
    {
        
        public GetCurrenciesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrenciesResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCurrenciesResponseBody Body;
        
        public GetCurrenciesResponse()
        {
        }
        
        public GetCurrenciesResponse(GetCountriesService.GetCurrenciesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetCurrenciesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrenciesResult;
        
        public GetCurrenciesResponseBody()
        {
        }
        
        public GetCurrenciesResponseBody(string GetCurrenciesResult)
        {
            this.GetCurrenciesResult = GetCurrenciesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyByCountryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyByCountry", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCurrencyByCountryRequestBody Body;
        
        public GetCurrencyByCountryRequest()
        {
        }
        
        public GetCurrencyByCountryRequest(GetCountriesService.GetCurrencyByCountryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetCurrencyByCountryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CountryName;
        
        public GetCurrencyByCountryRequestBody()
        {
        }
        
        public GetCurrencyByCountryRequestBody(string CountryName)
        {
            this.CountryName = CountryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyByCountryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyByCountryResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetCurrencyByCountryResponseBody Body;
        
        public GetCurrencyByCountryResponse()
        {
        }
        
        public GetCurrencyByCountryResponse(GetCountriesService.GetCurrencyByCountryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetCurrencyByCountryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrencyByCountryResult;
        
        public GetCurrencyByCountryResponseBody()
        {
        }
        
        public GetCurrencyByCountryResponseBody(string GetCurrencyByCountryResult)
        {
            this.GetCurrencyByCountryResult = GetCurrencyByCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGMTbyCountryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGMTbyCountry", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetGMTbyCountryRequestBody Body;
        
        public GetGMTbyCountryRequest()
        {
        }
        
        public GetGMTbyCountryRequest(GetCountriesService.GetGMTbyCountryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetGMTbyCountryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CountryName;
        
        public GetGMTbyCountryRequestBody()
        {
        }
        
        public GetGMTbyCountryRequestBody(string CountryName)
        {
            this.CountryName = CountryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGMTbyCountryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGMTbyCountryResponse", Namespace="http://www.webserviceX.NET", Order=0)]
        public GetCountriesService.GetGMTbyCountryResponseBody Body;
        
        public GetGMTbyCountryResponse()
        {
        }
        
        public GetGMTbyCountryResponse(GetCountriesService.GetGMTbyCountryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
    public partial class GetGMTbyCountryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGMTbyCountryResult;
        
        public GetGMTbyCountryResponseBody()
        {
        }
        
        public GetGMTbyCountryResponseBody(string GetGMTbyCountryResult)
        {
            this.GetGMTbyCountryResult = GetGMTbyCountryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public interface countrySoapChannel : GetCountriesService.countrySoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public partial class countrySoapClient : System.ServiceModel.ClientBase<GetCountriesService.countrySoap>, GetCountriesService.countrySoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public countrySoapClient(EndpointConfiguration endpointConfiguration) : 
                base(countrySoapClient.GetBindingForEndpoint(endpointConfiguration), countrySoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public countrySoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(countrySoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public countrySoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(countrySoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public countrySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<GetCountriesService.GetCountryByCountryCodeResponse> GetCountryByCountryCodeAsync(GetCountriesService.GetCountryByCountryCodeRequest request)
        {
            return base.Channel.GetCountryByCountryCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetCountriesService.GetISDResponse> GetISDAsync(GetCountriesService.GetISDRequest request)
        {
            return base.Channel.GetISDAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetCountriesService.GetCountriesResponse> GetCountriesAsync(GetCountriesService.GetCountriesRequest request)
        {
            return base.Channel.GetCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetCountriesService.GetCurrencyCodeByCurrencyNameResponse> GetCurrencyCodeByCurrencyNameAsync(GetCountriesService.GetCurrencyCodeByCurrencyNameRequest request)
        {
            return base.Channel.GetCurrencyCodeByCurrencyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetCountriesService.GetISOCountryCodeByCountyNameResponse> GetISOCountryCodeByCountyNameAsync(GetCountriesService.GetISOCountryCodeByCountyNameRequest request)
        {
            return base.Channel.GetISOCountryCodeByCountyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetCountriesService.GetCurrencyCodeResponse> GetCurrencyCodeAsync(GetCountriesService.GetCurrencyCodeRequest request)
        {
            return base.Channel.GetCurrencyCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetCountriesService.GetCountryByCurrencyCodeResponse> GetCountryByCurrencyCodeAsync(GetCountriesService.GetCountryByCurrencyCodeRequest request)
        {
            return base.Channel.GetCountryByCurrencyCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetCountriesService.GetCurrenciesResponse> GetCurrenciesAsync(GetCountriesService.GetCurrenciesRequest request)
        {
            return base.Channel.GetCurrenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetCountriesService.GetCurrencyByCountryResponse> GetCurrencyByCountryAsync(GetCountriesService.GetCurrencyByCountryRequest request)
        {
            return base.Channel.GetCurrencyByCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetCountriesService.GetGMTbyCountryResponse> GetGMTbyCountryAsync(GetCountriesService.GetGMTbyCountryRequest request)
        {
            return base.Channel.GetGMTbyCountryAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.countrySoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.countrySoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.countrySoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.webservicex.net/country.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.countrySoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.webservicex.net/country.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            countrySoap,
            
            countrySoap12,
        }
    }
}
